# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHeaderView, QMainWindow,
    QPlainTextEdit, QSizePolicy, QSplitter, QStatusBar,
    QTableView, QToolBar, QVBoxLayout, QWidget)
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(783, 587)
        self.actOpen = QAction(MainWindow)
        self.actOpen.setObjectName(u"actOpen")
        icon = QIcon()
        icon.addFile(u":/images/icons/open.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actOpen.setIcon(icon)
        self.actSave = QAction(MainWindow)
        self.actSave.setObjectName(u"actSave")
        self.actSave.setEnabled(False)
        icon1 = QIcon()
        icon1.addFile(u":/images/icons/save.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actSave.setIcon(icon1)
        self.actAppend = QAction(MainWindow)
        self.actAppend.setObjectName(u"actAppend")
        self.actAppend.setEnabled(False)
        icon2 = QIcon()
        icon2.addFile(u":/images/icons/append.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actAppend.setIcon(icon2)
        self.actInsert = QAction(MainWindow)
        self.actInsert.setObjectName(u"actInsert")
        self.actInsert.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(u":/images/icons/306.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actInsert.setIcon(icon3)
        self.actDelete = QAction(MainWindow)
        self.actDelete.setObjectName(u"actDelete")
        self.actDelete.setEnabled(False)
        icon4 = QIcon()
        icon4.addFile(u":/images/icons/delete.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actDelete.setIcon(icon4)
        self.actExit = QAction(MainWindow)
        self.actExit.setObjectName(u"actExit")
        icon5 = QIcon()
        icon5.addFile(u":/images/icons/exit.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actExit.setIcon(icon5)
        self.actModelData = QAction(MainWindow)
        self.actModelData.setObjectName(u"actModelData")
        icon6 = QIcon()
        icon6.addFile(u":/images/icons/export1.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actModelData.setIcon(icon6)
        self.actAlignLeft = QAction(MainWindow)
        self.actAlignLeft.setObjectName(u"actAlignLeft")
        icon7 = QIcon()
        icon7.addFile(u":/images/icons/508.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actAlignLeft.setIcon(icon7)
        self.actAlignCenter = QAction(MainWindow)
        self.actAlignCenter.setObjectName(u"actAlignCenter")
        icon8 = QIcon()
        icon8.addFile(u":/images/icons/510.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actAlignCenter.setIcon(icon8)
        self.actAlignRight = QAction(MainWindow)
        self.actAlignRight.setObjectName(u"actAlignRight")
        icon9 = QIcon()
        icon9.addFile(u":/images/icons/512.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actAlignRight.setIcon(icon9)
        self.actFontBold = QAction(MainWindow)
        self.actFontBold.setObjectName(u"actFontBold")
        self.actFontBold.setCheckable(True)
        icon10 = QIcon()
        icon10.addFile(u":/images/icons/500.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actFontBold.setIcon(icon10)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.splitter = QSplitter(self.centralwidget)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setGeometry(QRect(12, 12, 540, 225))
        self.splitter.setOrientation(Qt.Horizontal)
        self.groupBox = QGroupBox(self.splitter)
        self.groupBox.setObjectName(u"groupBox")
        self.verticalLayout = QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(4, 4, 4, 4)
        self.tableView = QTableView(self.groupBox)
        self.tableView.setObjectName(u"tableView")
        self.tableView.setAlternatingRowColors(True)
        self.tableView.setSortingEnabled(True)

        self.verticalLayout.addWidget(self.tableView)

        self.splitter.addWidget(self.groupBox)
        self.groupBox_2 = QGroupBox(self.splitter)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(4, 4, 4, 4)
        self.plainTextEdit = QPlainTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setLineWrapMode(QPlainTextEdit.NoWrap)

        self.verticalLayout_2.addWidget(self.plainTextEdit)

        self.splitter.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.toolBar.addAction(self.actOpen)
        self.toolBar.addAction(self.actModelData)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actAppend)
        self.toolBar.addAction(self.actInsert)
        self.toolBar.addAction(self.actDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actAlignLeft)
        self.toolBar.addAction(self.actAlignCenter)
        self.toolBar.addAction(self.actAlignRight)
        self.toolBar.addAction(self.actFontBold)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actExit)

        self.retranslateUi(MainWindow)
        self.actExit.triggered.connect(MainWindow.close)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"TableView-Demo", None))
        self.actOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actOpen.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.actSave.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actSave.setToolTip(QCoreApplication.translate("MainWindow", u"\u8868\u683c\u5185\u5bb9\u53e6\u5b58\u4e3a\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.actAppend.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u884c", None))
#if QT_CONFIG(tooltip)
        self.actAppend.setToolTip(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u4e00\u884c", None))
#endif // QT_CONFIG(tooltip)
        self.actInsert.setText(QCoreApplication.translate("MainWindow", u"\u63d2\u5165\u884c", None))
#if QT_CONFIG(tooltip)
        self.actInsert.setToolTip(QCoreApplication.translate("MainWindow", u"\u63d2\u5165\u4e00\u884c", None))
#endif // QT_CONFIG(tooltip)
        self.actDelete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u884c", None))
#if QT_CONFIG(tooltip)
        self.actDelete.setToolTip(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5f53\u524d\u884c", None))
#endif // QT_CONFIG(tooltip)
        self.actExit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#if QT_CONFIG(tooltip)
        self.actExit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
#endif // QT_CONFIG(tooltip)
        self.actModelData.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u9884\u89c8", None))
#if QT_CONFIG(tooltip)
        self.actModelData.setToolTip(QCoreApplication.translate("MainWindow", u"\u6a21\u578b\u6570\u636e\u663e\u793a\u5230\u6587\u672c\u6846\u91cc", None))
#endif // QT_CONFIG(tooltip)
        self.actAlignLeft.setText(QCoreApplication.translate("MainWindow", u"\u5c45\u5de6", None))
#if QT_CONFIG(tooltip)
        self.actAlignLeft.setToolTip(QCoreApplication.translate("MainWindow", u"\u6587\u5b57\u5de6\u5bf9\u9f50", None))
#endif // QT_CONFIG(tooltip)
        self.actAlignCenter.setText(QCoreApplication.translate("MainWindow", u"\u5c45\u4e2d", None))
#if QT_CONFIG(tooltip)
        self.actAlignCenter.setToolTip(QCoreApplication.translate("MainWindow", u"\u6587\u5b57\u5c45\u4e2d", None))
#endif // QT_CONFIG(tooltip)
        self.actAlignRight.setText(QCoreApplication.translate("MainWindow", u"\u5c45\u53f3", None))
#if QT_CONFIG(tooltip)
        self.actAlignRight.setToolTip(QCoreApplication.translate("MainWindow", u"\u6587\u5b57\u53f3\u5bf9\u9f50", None))
#endif // QT_CONFIG(tooltip)
        self.actFontBold.setText(QCoreApplication.translate("MainWindow", u"\u7c97\u4f53", None))
#if QT_CONFIG(tooltip)
        self.actFontBold.setToolTip(QCoreApplication.translate("MainWindow", u"\u7c97\u4f53\u5b57\u4f53", None))
#endif // QT_CONFIG(tooltip)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"TableView", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"PlainTextEdit", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

